/**
 * Export the current SQLite database to a portable, reloadable SQL dump at
 * scripts/sample-data.sql (schema + data, like `sqlite3 .dump`).
 *
 * Run with:  npm run dump
 *
 * Reload with either:
 *   sqlite3 ./data/supportnest.db < scripts/sample-data.sql
 *   npm run db:load
 */
import fs from 'fs';
import path from 'path';
import { db } from '@/lib/db';

const OUT = path.join(process.cwd(), 'scripts', 'sample-data.sql');

// Quote a value for a SQL literal.
function lit(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'bigint') return v.toString();
  if (Buffer.isBuffer(v)) return `X'${v.toString('hex')}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

function main() {
  // Tables in FK-safe order (parents before children).
  const tableOrder = [
    'Organizations',
    'Users',
    'Requisitions',
    'Candidates',
    'MatchScores',
    'HiringPhases',
    'DiagnosticReports',
    'SkillAssessments',
    'CandidateAssessmentResults',
    'InterviewPrepModules',
    'AllyshipModules',
    'UserAllyshipProgress',
    'AuditLogs',
  ];

  // Pull CREATE statements (tables + indexes) straight from the live schema.
  const schemaRows = db
    .prepare(
      `SELECT name, type, sql FROM sqlite_master
       WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
       ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END`
    )
    .all() as { name: string; type: string; sql: string }[];

  const tables = schemaRows.filter((r) => r.type === 'table');
  const indexes = schemaRows.filter((r) => r.type === 'index');

  const parts: string[] = [];
  parts.push('-- Support Nest — sample database dump');
  parts.push('-- Generated by scripts/export-sample.ts (npm run dump).');
  parts.push('-- Reload: sqlite3 ./data/supportnest.db < scripts/sample-data.sql');
  parts.push('');
  parts.push('PRAGMA foreign_keys=OFF;');
  parts.push('BEGIN TRANSACTION;');
  parts.push('');

  // Drop + recreate each table for a clean reload.
  for (const t of tables) {
    parts.push(`DROP TABLE IF EXISTS "${t.name}";`);
    parts.push(`${t.sql};`);
  }
  parts.push('');

  // Data, in FK-safe order (fall back to schema order for any extra tables).
  const ordered = [
    ...tableOrder.filter((n) => tables.some((t) => t.name === n)),
    ...tables.map((t) => t.name).filter((n) => !tableOrder.includes(n)),
  ];

  let totalRows = 0;
  for (const name of ordered) {
    const cols = (
      db.prepare(`PRAGMA table_info("${name}")`).all() as { name: string }[]
    ).map((c) => c.name);
    const rows = db.prepare(`SELECT * FROM "${name}"`).all() as Record<
      string,
      unknown
    >[];
    if (rows.length === 0) continue;
    parts.push(`-- ${name} (${rows.length} rows)`);
    const colList = cols.map((c) => `"${c}"`).join(', ');
    for (const row of rows) {
      const vals = cols.map((c) => lit(row[c])).join(', ');
      parts.push(`INSERT INTO "${name}" (${colList}) VALUES (${vals});`);
    }
    parts.push('');
    totalRows += rows.length;
  }

  // Recreate indexes after data load.
  for (const idx of indexes) {
    parts.push(`${idx.sql};`);
  }
  parts.push('');
  parts.push('COMMIT;');
  parts.push('PRAGMA foreign_keys=ON;');
  parts.push('');

  fs.writeFileSync(OUT, parts.join('\n'), 'utf-8');
  console.log(
    `✓ Wrote ${OUT}\n   ${tables.length} tables, ${totalRows} rows, ${indexes.length} indexes`
  );
}

main();
process.exit(0);
